CREATE DATABASE IF NOT EXISTS example;

use example;
CREATE TABLE IF NOT EXISTS user (
  id int(10) NOT NULL,
  name VARCHAR(16) NOT NULL,
  age int(10) NOT NULL,
  profile VARCHAR(64) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;